[[redirects]]
from = "/hf/*"
to = "https://hf-mirror.com/:splat"
status = 200
force = true
[[redirects]]
from = "/api/resolve-cache/*"
to = "https://hf-mirror.com/api/resolve-cache/:splat"
status = 200
force = true